services:
  monitor:
    build: .
    container_name: tp1_monitor
    tty: true
    stdin_open: true
    pid: host
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - ./src:/app/src
      - ./config.json:/app/config.json
